# App
APP_KEY: ""
APP_SECRET: ""

# 계좌번호 앞 8자리
CANO: ""
# 계좌번호 뒤 2자리
ACNT_PRDT_CD: ""

# 실전 투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
# 모의 투자
#URL_BASE: "https://openapivts.koreainvestment.com:29443"

# Discord Web Hook URL
DISCORD_WEBHOOK_URL: ""